### ISSUE TITLE
CGI Failure

### ISSUE THREAD

**Issue by HoloryTV** [dimok789/loadiine_gx2#100]
Hello guys, I am trying to self-host HBL or Loadiine.
I worked fine when I was 5.3.2 but now I am getting an error "cgi failure" when loading payloads.
And it works fine with "loadiine.ovh" or "wj44.ml"
And ServerHax.jar works too.

Thanks !

**Comment by drizzt** [comment]
It's not a problem of loadiine, but your webserver or PHP configuration.
For 5.3.2 you don't need to use PHP nor CGI at all

**Comment by HoloryTV** [comment]
Yes that's it.
I used Mongoose and now I am using wampp and it works.
Thanks for the reply !
