### ISSUE TITLE
I'd like to contribute with Memory Scan log of 5.1.0

### ISSUE THREAD

**Issue by Recchi** [dimok789/loadiine_gx2#106]
Hi!

Loadiine GX2 launches fine on 5.1.0 since quite a few builds. The problem is that most of the games just simply "blackscreen" (I think the only game that works fine is Mario Kart 8), even though they work fine with the 5.1.0 port of Loadiine V4.0 (and they also all work from disc). Tested with like 5-6 0.3 nightlies, including the most recent one.

I figured it must have something to do with the difference in memory layout on 5.1.0 compared to other firmwares. I just found dimok's Memory Scan in GBATemp's Loadiine GX2 thread and I wanted to post my log, but Memory Scan also "blackscreens" on 5.1.0.

If it's not too much to ask, could you please fix Memory Scan, so I can create and post a log from fw. 5.1.0? Thank you very much in advance and keep up the awesome work.

**Comment by BlaineMiller1988** [comment]
I don't believe you are correct sir.  You have a different problem if all of your games, except Mario Kart 8 are not working.  This seems strange because most people have reported here and on GBAtemp that mostly all games are working.  It might be your game dumps are corrupted.  You might also try formatting your sd card again with 64kb cluster size....

**Comment by Recchi** [comment]
Thank you for the advice good sir, but just as I said, **they all work fine with the 5.1.0 port of Loadiine V4.0** (this one: https://gbatemp.net/threads/loadiine-v4-for-5-0-0-5-1-0-wiiu.406324/), so the rips are fine. I'm using 32k clusters (64GB SDXC), but tried to copy 3 of my games to a different, smaller SD card (16GB SDHC) formatted to 64k clusters and everything was the same: they all worked with Loadiine V4.0, but only MK8 worked with Loadiine GX2.

**Comment by BlaineMiller1988** [comment]
That is weird.  Have you tried a different SD card? Just trying to iron out the difference in experience with loadiine GX2 from your own.

**Comment by Recchi** [comment]
Yes I have, just as I've explained in my previous post... Also just to make sure we are on the same page, I'm on the fairly old fw. **5.1.0**, and not the most recent 5.5.1.

**Comment by BlaineMiller1988** [comment]
Yep, I read the incorrectly which makes it more interesting.  Thanks for clarifying.

**Comment by dibas** [comment]
Closing this issue to continue discussion in #118.
