### ISSUE TITLE
[Feature Request] Load game from http/ftp server instead memory card.

### ISSUE THREAD

**Issue by abelardoam** [dimok789/loadiine_gx2#107]

**Comment by mariogamer2** [comment]
In fact,this is a good idea,but with the speed of the internet of the Wii U and the game size....

**Comment by CreeperMario** [comment]
@mariogamer2 is correct. Internet connection speeds will severely affect your experience. If it took 7 hours to dump Smash Bros. using DDD (16GB) I can only imagine how long it would take to actually load a single file.

**Comment by mariogamer2** [comment]
Not a good idea. Maybe from localhost,but, for this,you need to buy a little server to have a good speed....

**Comment by CreeperMario** [comment]
@mariogamer2 and a solid, 100mb/s network (unlike my $10 8mb/s modem).

**Comment by Maschell** [comment]
Would be way to slow. At the moment the network speed for us is limited @ ~10Mbit, look at the ddd dumping speed to get an idea of how slow this would be.

**Comment by abelardoam** [comment]
The idea is to mount a local ftp. You can use Wii LAN Adapter(10mb/s) or try a connection, as fast as possible, by wifi (802.11n max 600mb/s with exclusive access point for Wii U) on local network server.

**Comment by tranaconda** [comment]
@abelardoam Are you aware of the difference between MegaBit and MegaByte? @Maschell just told you we're locked at about 10 MegaBit, which is ~1,25 MegaByte - not counting overhead (which would reduce it to below one MegaByte probably). Loading times would be **abysmal**.

And I think you're confusing 802.11n (150 MegaBit brutto, really less than 100 MegaBit) with 802.11ac (600 MegaBit or 1200 MegaBit with two antennas). But this is only if you have good chipsets, which the WiiU doesn't have. @CreeperMario pointed out ddd's backup speed, this is probably what you can expect the other way around. Then there's random access.

All in all - nice Idea, but most likely not worth it. You'll have to buy a good SD card.

**Comment by bijita1** [comment]
Well it's a good idea if you use a partage connection from a device you control it will give in theory about the same if not less than a SD card but why not use a USB TO MICRO SD Converter you could use any type of usb or even some external hard drive i will send in my next comments the linke for the device if you are interested it will give you some info about it

**Comment by bijita1** [comment]
here is the image of the device            http://www.blogcdn.com/www.engadget.com/media /2009/05/elan-mobidapter-1.jpg

**Comment by bijita1** [comment]
http://www.blogcdn.com/www.engadget.com/media/2009/05/elan-mobidapter-1.jpg

**Comment by CreeperMario** [comment]
@bjita1 interesting... but is it more effective? I mean in terms of data transfer speed and overall cost?
I do realise that this means we can connect a full HDD to Loadiine, but is it any faster or cheaper than a 128GB SD Card?

**Comment by bijita1** [comment]
A sdhc cost about 94,99$ the mobiadapter in 39,55$ and usd is about 47,67$ and if we add more usb to the all then i think all of us know the results form then

**Comment by bijita1** [comment]
By the way usb and Sd card are both of 128gb the cheaper one for SD CARD and sony one for the USB

**Comment by bijita1** [comment]
@CreeperMario as you can see it is but as for external hard drive only those how have a separate energy supply (two USB one for data and one for energy) cause the device don't enough energy output to make it work

**Comment by dibas** [comment]
Everything regarding loading games over a network connection has been said, it all comes down to the network speed being too low for pleasant loading times. I'm closing this issue.
