### ISSUE TITLE
DLC PACKAGE PROBLEM 

### ISSUE THREAD

**Issue by bijita1** [dimok789/loadiine_gx2#111]
Well i did all the necessary but it still locked when i use loadiine gx2v0.3

**Comment by bijita1** [comment]
Thanks for the hard work i'm always glad for the work you put all of you on this project

**Comment by CreeperMario** [comment]
I've never used DLC within Loadiine GX2 before. Before the program had official support for DLC, people just dumped the DLC along with the actual game.

With the DLC (and any updates) installed on the console, using [dimok789/ddd](https://github.com/dimok789/ddd) to dump the game will also dump the updates and DLC into one package, that SHOULD work in Loadiine.

That's how people used to do it, until having DLC installed on the console was enough to have it loaded in Loadiine. I'm still not aware on how that works without IOSU access.

**Comment by bijita1** [comment]
Thanks i will try it using ddd again

**Comment by bijita1** [comment]
@CreeperMario thanks by the way i found something that I didn't know that is if you get the DLC it don't unlock them but remplace some existing one i tast it in mario kart 8  and it remplaced the first four cup with the DLC ONE

**Comment by CreeperMario** [comment]
@bijita1 so the Mushroom, Flower, Shell and Banana Cups were replaced, huh?
I purchased the DLC, and run Mario Kart 8 from disc, and the new cups are separated from the originals.

"Any progress is better than no progress." - Probably someone from the 1800s.

**Comment by dibas** [comment]
I'm closing this issue. Please use the issues page appropriately, for other questions/feedback you can use the support thread on gbatemp.
