### ISSUE TITLE
Loadiine gui crash

### ISSUE THREAD

**Issue by alexsmile00** [dimok789/loadiine_gx2#122]
Loadiine crash when selected a game by touchscreen

**Comment by dibas** [comment]
Please tell us your system version, the version of Loadiine you are using, any connected peripherals (like if and which controllers are connected) and add reproducible steps that lead to the crash. Thank you!

**Comment by dibas** [comment]
Closing this issue. Please post more info about the bugs you experienced in the previous issue you created (#119).
