### ISSUE TITLE
gx2_types.h not found with latest dynamic_libs

### ISSUE THREAD

**Issue by mariogamer2** [dimok789/loadiine_gx2#123]
/home/*/libwiiu/loadiine_gx2/src/gui/GuiElement.h:35:36: fatal error: dynamic_libs/gx2_types.h: No such file or directory
 #include "dynamic_libs/gx2_types.h"

Dynamic libs is up-to-date.

**Comment by CreeperMario** [comment]
```
#include "dynamic_libs/gx2_types.h"    // This works for files inside the main src folder, but not for files inside other sub-folders (such as the gui folder that GuiElement.h is located in).
#include "../dynamic_libs/gx2_types.h" // This snippet fixes sub-folder linking, but don't perform this on files inside the main src folder.
```
I hope that helps. (Just to clarify, use the second line to fix this error).

**Comment by mariogamer2** [comment]
Same thing. It seem like the file does not exist when searching it.

**Comment by mariogamer2** [comment]
No,it's strange,it seem like the submodule is not totally downloaded...
