### ISSUE TITLE
The Games wont start

### ISSUE THREAD

**Issue by LeonKuro** [dimok789/loadiine_gx2#131]
i had no problem lauching homebrew and loadiine.
my problem is, when i get to select a game from the list, it shows some options, so i accept touching "O.K." and then a bar that seems to display "loading game" appears and disappears, 
aaaaaand

nothing...

it simply closes the options window and i can freely move and even enter on config of loadiine...

**Comment by aaron456** [comment]
You didn't extract your game properly. Extract the zip/rar dump you might have downloaded with 7zip or keka. Because some file is corrupt in the game due to bad extraction, the game doesn't boot up. Also format your SD card to fat32.

**Comment by LeonKuro** [comment]
Aaaaaaand finaly i tested it. It was my microSD that was saying "copying" but when it finishes it automatically erases the files -.-
I bought another one 64gb c10 and it worked perfectly <3
Thanks
