### ISSUE TITLE
WHAT?!?!?!?!

### ISSUE THREAD

**Issue by NintendoWiiGuy** [dimok789/loadiine_gx2#132]
i have no idea what to do... i have the brain capacity of a 3yr old... i swear..
if someones got this on sd card...
send me a copy...
because i cant do it for my life

**Comment by CreeperMario** [comment]
Um... what exactly are you asking?
Do you want a copy of the file structure for Loadiine GX2 to run?

**Comment by VIRACY** [comment]
Buddy, it isn't the Clone or Download button on the main page.  That gives you all of the open source code and stuff that dimok is currently working on.  You have to get the files from the Releases page.  But here, I'l just give you the direct link to that page. https://github.com/dimok789/loadiine_gx2
