### ISSUE TITLE
Add support for creating shared and unique save at the same time

### ISSUE THREAD

**Issue by mariogamer2** [dimok789/loadiine_gx2#136]
As the Wii U do this,does it is possible to do this in loadiine?

**Comment by CreeperMario** [comment]
I haven't used Loadiine GX2 very much, but I'm pretty sure that if you set it to unique mode, it creates a `common` folder for all users on your console, and then a `8000000x` user for each user on your console. This is just like how the Wii U works.

Correct me if I'm wrong.

**Comment by Maschell** [comment]
Thats correct. The Uniquemode is just like the WiiU is handling the saves. The shared mode is just for compatibility reasons with older loadiine version (And of course a few people who really want to share the save between profiles)

**Comment by mariogamer2** [comment]
Ok thank.
