### ISSUE TITLE
error 160-2246 when loading new super luigi u loadline 0.2

### ISSUE THREAD

**Issue by andrew134** [dimok789/loadiine_gx2#141]
hi

I have a problem. every time I load new super luigi u in loadline it comes up woth error 160-2246 and it tells me to press and hold power button for four seconds. this problem started to happen two days ago and I keep getting it, any help of how to fix it please?

**Comment by CreeperMario** [comment]
"If you are receiving this error code, please contact us at 1-800-255-3700. Specially trained representatives will be available to assist you, 6:00am - 7:00pm (PST), seven days a week."
That's all I could find out about this error, but I doubt Nintendo would be able to help with Loadiine.

Most issues in Loadiine GX2 are related to SD Card formatting issues. Is your SD Card formatted as FAT32 with 64kb clusters? Is the folder structure set up correctly? That's all I can think of.

**Comment by andrew134** [comment]
yes, it is formatted to 64 cluster size and its fat32 and have the folder structure setup correctly. the game was working two days ago but now that error code appears every time I load it. I don't think it's a good idea to contact nintendo., i've heard deleting the cos.xml and app.xml might make problem go off but i tried that and it doesn't, any other solutions?

**Comment by andrew134** [comment]
yes, it is formatted to 64 cluster size and its fat32 and have the folder structure setup correctly. the game was working two days ago but now that error code appears every time I load it. I don't think it's a good idea to contact nintendo., i've heard deleting the cos.xml and app.xml might make problem go off but i tried that and it doesn't, any other solutions?

**Comment by andrew134** [comment]
yes, it is formatted to 64 cluster size and its fat32 and have the folder structure setup correctly. the game was working two days ago but now that error code appears every time I load it. I don't think it's a good idea to contact nintendo., i've heard deleting the cos.xml and app.xml might make problem go off but i tried that and it doesn't, any other solutions?

**Comment by andrew134** [comment]
good news I just made new super luigi u load correctly again by downloading the latest loadline nightly.
