### ISSUE TITLE
mario kart 8 dlc

### ISSUE THREAD

**Issue by andrew134** [dimok789/loadiine_gx2#142]
hi 

does anybody know how to make the mario kart 8 dlc work in mii maker mode?. there supposed to be a nighly build of loadline which supports all launch modes when using dlc.

**Comment by CreeperMario** [comment]
This is a problem with the way Mario Kart 8 maps its memory. Unfortunately, if you want to use an updated/dlc-ed version of Mario Kart 8, you will need to use Smash Bros. to launch it. Mii Maker is not compatible.

**Comment by andrew134** [comment]
ok, but like I said there is a loadline nightly update which says that dlc is compatible with all launch modes, lokk at the releases. also I read that to play the dlc tracks you need to change the main courses in the game with the dlc ones.

**Comment by andrew134** [comment]
ok, but like I said there is a loadline nightly update which says that dlc is compatible with all launch modes, look at the releases. also I read that to play the dlc tracks you need to change the main courses in the game with the dlc ones.

**Comment by CreeperMario** [comment]
Yes, DLC itself is supported on all launch modes.
There is an issue with Mario Kart 8, that only allows the original, unmodified, un-updated game to be launched in Mii Maker mode. I'm not quite sure why this happens.

If you really want to launch Mario Kart 8 with its DLC, you _will_ need to use Smash Bros. to launch it.

**Comment by andrew134** [comment]
ok, do I need the smash bros disc lr can I download it loadline ready and launch the mario kart 8 dlc from there?

**Comment by CreeperMario** [comment]
You will need the Smash Bros. disc, or an eShop download of Smash Bros. No way of pirating your way out of this one. 😜
