### ISSUE TITLE
How to compile Loadiine GX2?

### ISSUE THREAD

**Issue by Leseratte10** [dimok789/loadiine_gx2#15]
I've tried compiling Loadiine after adding the portlibs and libogc to my devkitPro folder and PATH, the object files get created, but linking fails with the following error: 

```
linking ... loadiine_gx2.elf
/home/florian/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/4.8.2/../../../../powerpc-eabi/bin/ld: /home/florian/devkitPro//libogc/lib/wii/libmad.a(frame.o): the target (mad_timer_zero) of a R_PPC_EMB_SDA21 relocation is in the wrong output section (.data)
/home/florian/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/4.8.2/../../../../powerpc-eabi/bin/ld: /home/florian/devkitPro//libogc/lib/wii/libmad.a(frame.o): the target (mad_timer_zero) of a R_PPC_EMB_SDA21 relocation is in the wrong output section (.data)
/home/florian/devkitPro/devkitPPC/bin/../lib/gcc/powerpc-eabi/4.8.2/../../../../powerpc-eabi/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
/home/florian/loadiine_test/load/Makefile:161: recipe for target '/home/florian/loadiine_test/load/loadiine_gx2.elf' failed
make[1]: *** [/home/florian/loadiine_test/load/loadiine_gx2.elf] Error 1
Makefile:139: recipe for target 'build' failed
make: *** [build] Error 2
```

Any idea what the problem might be?

(Also, the object files aren't even compiled (crash in the very beginning) when the path where the source is in contains spaces)

**Comment by scuba156** [comment]
do a `make clean`, then do a  `make` again

**Comment by Leseratte10** [comment]
That didn't change anything, I still get the same error.

**Comment by dimok789** [comment]
Use libmad.a from my libogc package. I had to modify it to not use sdata section. Replace your libogc libmad.a

**Comment by Leseratte10** [comment]
I would have bet that I've already replaced the content of my libogc folder with yours, but apparently this was not the case - removed my libmad.a from the folder and added yours again and compiling works. Thanks.

**Comment by dimok789** [comment]
I cant tell you what is wrong with your compile as I dont really know your setup.

About the issue that it doesnt compile when there is a space....its not a loadiine issue. Its a toolchain issue. No need to create an issue for that as i would only have to close it without being able to do anything.
