### ISSUE TITLE
Mario Party 10 issue

### ISSUE THREAD

**Issue by Giggy36** [dimok789/loadiine_gx2#155]
I have Mario Party 10 (USA Version) copied straight from the disc using ddd dumper and when loading gets to the first screen that says Mario Party 10 and freezes without any sound or movement.

**Comment by boullose** [comment]
delete the update (v16), run without update.

**Comment by Giggy36** [comment]
v16 on my Wii u memory or you mean on the DDD dumper backup

**Comment by Maschell** [comment]
Mario Party 10 has many RPL files that are dynamicly loaded. DDD only dumps the loaded ones (Everytime a RPL gets loaded, it will be dumped).
Maybe some of the rpl files are missing? (The EUR rip has 91 rpl files)

**Comment by Giggy36** [comment]
Ok sorry, what does that mean too me... I'm not sure what you are saying or telling me I should do...

**Comment by Maschell** [comment]
That maybe some files were not dumped.
Check your code folder if it has many .rpl files.

**Comment by Giggy36** [comment]
I cleaned the disc and after playing it for a little bit it played just fine!!!!
