### ISSUE TITLE
Problem with GX2 (The GRaphics Utility, not Loadiine)

### ISSUE THREAD

**Issue by NexoCube** [dimok789/loadiine_gx2#18]
I know, this is not really an issue, but can you make for me (please :c) a gx2 homebrew example with a glowing cube like this : (Very simple)

![test](https://cloud.githubusercontent.com/assets/13999756/13027840/89fe401a-d25e-11e5-880b-c4dde285b480.png)

Without, the background image, without the games icon, without the text. 

Just with the cube and the white tile 

And i'll be very happy if you do then :) (Because, i have on my <PC all the gx2 functions but idk how to use it. :c

**Comment by NexoCube** [comment]
Oh, and the mirror effect too ,

Pleaaaaaase, Dimok you are my god.

**Comment by n1ghty** [comment]
Commandment #1: You shall not misuse the issue ticket system.

**Comment by NexoCube** [comment]
Yes xD i know but i don't know how to contact dimok so...

**Comment by Mrrraou** [comment]
It's not even a problem. And do it yourself if you want it... I think it's fine enough like this. Plus, adding a mirror effect to it is not that simple...

**Comment by dimok789** [comment]
Not an issue and there is an example like this now on the forums. Closing...
