### ISSUE TITLE
multilanguage support?

### ISSUE THREAD

**Issue by littlebalup** [dimok789/loadiine_gx2#25]
I open this issue as a kind of "todo" and/or "how to do"... if agree to do :)

Personally I'm unable to start it from scratch due to my lack of c/c++ skills but so far it does not prevent me thinking about it. So I have some questions in mind that I hope may help you to define a strategy (if not already defined).

quetions are:
- Are we able to get language from the SCI? (like SCIGetCafeLanguage and/or SCIGetLanguageCodeA2 fonctions of cafeSDK).
- If not (yet) able to get language from SCI , manualy set language in menu settings?
- Were/how to store strings? in code? external SD file ?
- How to parse and manage strings (external lib??)

**Comment by dimok789** [comment]
gettext library is what we used in USB Loader GX.

You just have to do tr("some C string") and you get a file with those strings and can write the translation to them. Worked quite well.

**Comment by dimok789** [comment]
done
