### ISSUE TITLE
development environment setting

### ISSUE THREAD

**Issue by FunThomas76** [dimok789/loadiine_gx2#26]
Hi Dimok,
it would be good if you could give some default settings when trying to help you making changes in loadiineGX2.

I see that your files use CRLF and not the unix format. it would be good to find a layout preference for tabs/spaces because some files have some strange indent.

best regards,
Thomas

**Comment by dimok789** [comment]
That is wrong. The files use unix format. Your git probably checked them out as CRLF which is a setting in your git.

**Comment by FunThomas76** [comment]
what about the indent preference -> only use 2 or 4 spaces ?

**Comment by dimok789** [comment]
This depends on the editor of the developer. I can not influence that. Maschell might have been the one that checked in the 2 spaces code part. I always have 4 spaces. I use codeblocks most of the time to write the code. Anyway i am closing this issue as this is not really an issue
