### ISSUE TITLE
Unpredictable Cover Carousel

### ISSUE THREAD

**Issue by scuba156** [dimok789/loadiine_gx2#29]
Steps to reproduce: 
1. Copy a high amount of titles to sdcard (discovered with 68 items)
2. Start loadiine using Cover carousel
3. Press right, left, L or R

Expected result: 
- Pressing left/right should go to the next/previous title
- L/R should go forward/back 5 titles

Actual result: 
- Movements are entirely random, sometimes moving 1 title forward/back, usually doing a 360 degrees rotation + 1 title. Sometimes going right when pressing left and vice versa.
- Double tapping L/R will move it 5 places, otherwise it will do a 360 rotation + 5
- When the carousel is almost stopped, the title display will flicker between multiple titles as if it can't decide where it will land

**Comment by scuba156** [comment]
Bad Quality video of the issue:
https://goo.gl/photos/MuEjP2fUPABs8yRX7

**Comment by PR0r** [comment]
I don't have 68 items like you do but I believe I've experience this "issue" when my gamepad has a different view to the TV. If the gamepad and tv have the same view I have had no issues with this issue.

**Comment by littlebalup** [comment]
This issue should have been fixed since the introduction of the GameStartIndex parameter. Please try latest official beta released v02 : https://github.com/dimok789/loadiine_gx2/releases

**Comment by dimok789** [comment]
Please re-test this. I fixed it. It does a full endless circle now on a game amount > 14.
