### ISSUE TITLE
Pb with hidden file

### ISSUE THREAD

**Issue by RobertNNms** [dimok789/loadiine_gx2#41]
Hi,

I prepare my SD Card with my mac (os x), and the problem, the os x create hidden files on each folder visited.
In the folder games/my game/code, os x create an hidden file of rpx (example: _main.rpx), and gx launch the first find file (_main.rpx instead of main.rpx) -> result : display the name file then crashed.

Regards

**Comment by HoloryTV** [comment]
My games are displayed but not working - 1st solution : 

If you are using a Mac, you need to delete the hidden data (the file or folder starting with "._" prefix. example)
You can delete them manually or use a program like "hidden cleaner".

**Comment by dibas** [comment]
I just pushed a fix regarding this issue. Please report back whether it works for you. You can find the nightly here: https://github.com/dimok789/loadiine_gx2/releases/tag/Loadiine-nightly-a5a7dcf
