### ISSUE TITLE
What are the dependencies needed to compile this?

### ISSUE THREAD

**Issue by Guy50570** [dimok789/loadiine_gx2#46]
Having some trouble compiling. I don't think I have all the dependencies needed. What are they? Thanks

**Comment by mariogamer2** [comment]
Me too...I didn't compil wiiu apps these time,more 3ds....

**Comment by mariogamer2** [comment]
Just compiled!!!!

Put this in the libwiiu folder,run make installer....

**Comment by mariogamer2** [comment]
ARGGG

GLM is not found...

**Comment by mariogamer2** [comment]
@dimok789 glm is always not found....

**Comment by mariogamer2** [comment]
Other problem...

linking ... loadiine_gx2.elf
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/4.8.2/../../../../powerpc-eabi/bin/ld: /opt/devkitpro/libogc/lib/wii/libmad.a(frame.o): the target (mad_timer_zero) of a R_PPC_EMB_SDA21 relocation is in the wrong output section (.data)
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/4.8.2/../../../../powerpc-eabi/bin/ld: /opt/devkitpro/libogc/lib/wii/libmad.a(frame.o): the target (mad_timer_zero) of a R_PPC_EMB_SDA21 relocation is in the wrong output section (.data)
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/4.8.2/../../../../powerpc-eabi/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
/home/***/libwiiu/loadiine_gx2/Makefile:163: recipe for target '/home/nour/libwiiu/loadiine_gx2/loadiine_gx2.elf' failed
make[1]: *** [/home/***/libwiiu/loadiine_gx2/loadiine_gx2.elf] Error 1
Makefile:141: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by mariogamer2** [comment]
Also it's not normal that, for build,it's need sudo (and maybe admin colsole on windows) for build....

**Comment by dimok789** [comment]
You dont need sudo for build. I build under user login on my linux. Your issue is that you didnt use the libogc from the release site and maybe even forgot the portlibs.
https://github.com/dimok789/loadiine_gx2/releases/tag/v0.2

**Comment by mariogamer2** [comment]
Didn't forgot portlib but forgot libogc :D
Sorry...

**Comment by mariogamer2** [comment]
also,when using make normal, it's giveme that the not granted permission.

**Comment by dimok789** [comment]
This is an issue because you set the permissions on those folders like that. Just change those permissions to allow "user" and maybe "others" to read that folder (recursivly). Its not a general issue, its just your setup.

**Comment by mariogamer2** [comment]
Oh,it's was because I copied libogc and portlibs as sudo,changing the properties is ok...
