### ISSUE TITLE
Autostart Game Option

### ISSUE THREAD

**Issue by Kekskruemel** [dimok789/loadiine_gx2#5]
Hi,

first thx for the job.

Maybe you can add later any option to autostart the game if there is only one detected.

It's a bit special request, but I play on the wii u very often remotely. Streaming the picture with my nvidia shield and send input with gimx and gc to vpad to the wii u.

Sadly I can't choose any game because gc to vpad doesn't work in the menu, same with my harmony smart hub from logitech which can send remotely commands like with a wii mote.

I was able to edit the code in loadiine 4 but this code here is to complex for my little programming skills.

Thx & Bye

**Comment by Toastytwo** [comment]
Hello Kekskruemel,

can you explain how your streaming solution works?
Sounds really awesome....
Gerne auch auf deutsch... ;)

**Comment by dimok789** [comment]
I could do that but I will add a setting that you will have to activate to autostart a game. Probably gonna make it an index or something for the game (0 = game 1, 1 = game 2....).

I dont know how you would want to go about stopping loadiine to autoboot though. Probably will have to delete config or modify it manually.

**Comment by Relys** [comment]
@Toastytwo I assume he has a capture card and uses the Nvidia GameStream protocol. 

Not sure why https://github.com/FIX94/gc-to-vpad wouldn't work within the menu as it hooks into the VPADRead function (unless Loadiine is using some other method)? Should be easy enough to fix.

It would be easy enough to add a little handler listening on a port and running in a separate thread which could take RESTish API calls to interact with Loadiine menu. Similar type deal to https://github.com/Matsumot0/webMAN-MOD

**Comment by Kekskruemel** [comment]
@dimok789 thx for the answer.

Maybe pressing a button to cancel autoboot which would start after 30 seconds or so. Deleting or changing a setting would also be fine.

@Toastytwo 

I am using a avermedia extreme cap u3 capture card which have a very low latency in the live view.

For the controls I use a teensy with this firmware http://procrastineering.blogspot.de/2010/12/simulated-ps2-controller-for.html which emulates a ps2 controller. I can send commands via the software gimx (but only a older version, the newer one doesnt have ps2 support). So I can map my gamepad inputs which also get send via steam in home streaming or nvidia gamestream. Then I use a ps2 to gc adapter which is connected to the gc adapter for wii u smash.

With gc to vpad which is mentioned by relys I can then play wii u games remotely.

A bit complex, but working perfect for me.

Also using capture card and gimx to play remotely ps3/xbox classic/360/one and ps4.

**Comment by Kekskruemel** [comment]
Request isn't required anymore for me, because the change to control the gui with wii mote fixed my "problem".

I am able to switch games remotely with the harmony hub which emulates a wii mote.

But fell free to add the autostart feature if you wish, maybe it's handy for someone else.

Thx for your work
