### ISSUE TITLE
re-opening loadiine from wiiu menu / Mii maker will crash if AppLanguage is set in .cfg

### ISSUE THREAD

**Issue by littlebalup** [dimok789/loadiine_gx2#55]
Should be:
Once loaded via sd_loader then exited via home button, We can re-open loadiine from the wiiu menu / Mii maker icon. 

Is: 
If AppLanguage value is set in the cfg file (as "french" in my case), it will load correctly the first time via sd_loader. But will crash/freeze on Mii Maker opening screen if re-launched from the wiiu menu. Reseting AppLanguage value to nothing fix the issue.

Not tested thru HBL.

Edit: no issue via official HBL 1.01

**Comment by dimok789** [comment]
Ok fixed it. It is an issue with the FILE C standard for file accessing. It doesn't work if you dont clear BSS section correctly and we don't do it in loadiine because we want it to have retain data areas. I didn't test it, just made a quick fix. If you could confirm it working that would be great.

**Comment by littlebalup** [comment]
Very good job, as always. Works like a charm :+1:
