### ISSUE TITLE
KARAOKE and Art Academy Atelier alternatives?

### ISSUE THREAD

**Issue by littlebalup** [dimok789/loadiine_gx2#6]
Please, could you add those as lauching games? 
https://gbatemp.net/threads/alternative-loadiine-4-1-mlt.404599/#post-5837726

Personnaly, I'm using Art atelier just fine (but not seems to have online / miiverse support).
RPX name : Treasure.rpx

Thanks.

**Comment by dimok789** [comment]
Yeah I can add that. Its not like its a lot of work. Will add it tommorow as I wont get to it today anymore.
