### ISSUE TITLE
Games not even in loadiine 

### ISSUE THREAD

**Issue by Phenix54s** [dimok789/loadiine_gx2#71]
Loadiine-nightly-7e4313d : games are not even  in the loadiine menu  like if they are'nt on SD card , but they are in SD card :)

**Comment by dimok789** [comment]
Maschell can you take a look at this? It looks like an issue with your stuff maybe? Also a setting for that stuff would be great so it is not always applied.

**Comment by dimok789** [comment]
Ok wrong issue. Maschell.

@Phenix54s 
You need to setup the game folders in a correct format. Check out the forum on how that works and ask in the thread if you need help with that.
