### ISSUE TITLE
problem with last nightly build.

### ISSUE THREAD

**Issue by airkingbr** [dimok789/loadiine_gx2#76]
With last nightly build, loadiine dont work with 5.5.1, crash on movie screen.
if i put an old loadiine build ... that works normal.

**Comment by kavid** [comment]
[Chinese_v0.33.zip](https://github.com/dimok789/loadiine_gx2/files/249978/Chinese_v0.33.zip)

This is Chinese.lang and Chinese_tr.lang v0.33,pls upload them to github.
