### ISSUE TITLE
add icon.png and xml to the release

### ISSUE THREAD

**Issue by blairfancy** [dimok789/loadiine_gx2#83]
Hi,
Could you add icon and xml for homebrew launcher?

**Comment by HoloryTV** [comment]
You can take them from stable release

**Comment by drizzt** [comment]
Or, better, you can choose you icon and download the updated (with 0.3 version) xml here https://github.com/dimok789/loadiine_gx2/tree/master/meta

**Comment by mariogamer2** [comment]
Exactly like @drizzt sayd.
