### ISSUE TITLE
[Feature Request] Kick back to Wii U Menu when using Smash Bros Disk message

### ISSUE THREAD

**Issue by teconmoon** [dimok789/loadiine_gx2#84]
When launching a game such as Mario Kart 8 + DLC or Wii Sports Club that currently need to be launched though the Smash Bros Disk Message, is it possible to get kicked back to the Wii U Menu immediately where you can launch Smash Bros instead of having to quit Mii Maker first?

Only reason I ask is DDD and Saviine quit right to the Wii U Menu instead of having to quit Mii Maker, I would ask if it's possible down the line if the Smash Bros Disk method could just automatically launch the disk, but even though DDD and Saviine show launching the disk as a feature it doesn't really work LOL

Anyways thanks for reading! This isn't really necessary, but could make for a more fluid transition from loader to game.

**Comment by dimok789** [comment]
I will change the direct disc launch method later to work every time. Might not skip the SSBU update nagging though but since you got that on system menu too, i guess you don't loose anything.

**Comment by teconmoon** [comment]
Nice good luck! Rooting for ya :+1: Smash Bros is currently up to date on my Wii U so it doesn't nag me to update, unless you're talking about something different that's going over my head

**Comment by dimok789** [comment]
This should be done now with last commit.
