### ISSUE TITLE
Add multi controller support from HID to VPAD

### ISSUE THREAD

**Issue by SirBeethoven** [dimok789/loadiine_gx2#85]
Would you be able to add multicontroller support from the HID to VPAD extension in your code?

Edit - Meaning to add multiple controllers at a time

AND - to change the ZR and ZL to R and L by default on VC games

AND - to add a controller config

**Comment by Maschell** [comment]
What do you mean exactly? Loadiine does support hid to vpad from thefirst day it way released

**Comment by SirBeethoven** [comment]
I mean like having multiple controllers at once. Right now, I can't play multiplayer on Mario Kart 64 VC or Super Smash Bros 64 VC. HID to VPAD only interpenetrates the controllers connected to the WiiU controller. Also it would be nice if for VC games, that you wouldn't have to hold the Z button and press R to make it actually interperate the R button - VC games don't use LR at all

**Comment by dibas** [comment]
This isn't a Loadiine improvement in itself, it should be posted here: https://github.com/Maschell/hid_to_vpad
