### ISSUE TITLE
Post memory scanner log here

### ISSUE THREAD

**Issue by mariogamer2** [dimok789/loadiine_gx2#88]
https://gbatemp.net/threads/loadiine-gx2.413823/page-181#post-6331866

**Comment by Draky50110** [comment]
Hello.

Firm = 5.5.1 / EUR.
Launched Super Smash (original disc) after returning to menu.
Game crashed after scanner, just after the messages about SD.
[551_EUR_GeckoLog.txt](https://github.com/dimok789/loadiine_gx2/files/255779/551_EUR_GeckoLog.txt)

If anything else needed...
Have other original games.

**Comment by KitBallard64** [comment]
http://www.mediafire.com/download/88jvzpidkuw8cbx/GeckoLog_-_WiiU_5.5.1U.txt

Here's mine. 5.5.1U. Launched a couple of other titles too. Never know.
Order Accessed:
Mii Maker, Smash 4, Super Mario Maker, Monster Hunter 3, Hyrule Warriors, Splatoon.

**Comment by ol100** [comment]
@Draky50110 

i have the same file (5.5.1/EUR) with mii maker and smash, but it didn´t crash for me, the log file is ok.

**Comment by KitBallard64** [comment]
Eh, why not. Here's a few "On System" games.
[GeckoLog - WiiU 5.5.1U Pt2.txt](https://github.com/dimok789/loadiine_gx2/files/255822/GeckoLog.-.WiiU.5.5.1U.Pt2.txt)
Launch order:
Mii Maker, Legend of Zelda: Wind Waker, Virtual Console: Super Punchout!, Mini Mario & Friends amiibo Challenge, Fatal Frame: Maiden of Black Water ("Demo") (Last string was from going to menu)

**Comment by dimok789** [comment]
Thanks. I will wait for other firmwares and add them all at once.

**Comment by Katkat95** [comment]
Firm = 5.5.1 / EUR.
Karaoke / Hyrule Warriors / Splatoon
[GeckoLog.txt](https://github.com/dimok789/loadiine_gx2/files/255844/GeckoLog.txt)

**Comment by Bionov** [comment]
Firm = 5.5.1 - EUR
Yoshi's Wooly world / Smash bros
https://github.com/Bionov/MemScan-WiiU-5.5.1-EU/blob/master/GeckoLog.txt

**Comment by nexusmtz** [comment]
Firm = 5.4.0 - U
Smash Bros (disc) / Mario Kart (preload)/ Nintendo Land (disc)
[GeckoLog_540U_nexusmtz.txt](https://github.com/dimok789/loadiine_gx2/files/256250/GeckoLog_540U_nexusmtz.txt)

**Comment by steff75** [comment]
Firm = 5.5.1  EUR
[GeckoLog_5.5.1  EUR.txt](https://github.com/dimok789/loadiine_gx2/files/256785/GeckoLog_5.5.1.EUR.txt)
amazon prime video, youtube, several humble bundle games

**Comment by dimok789** [comment]
Thanks to everyone! I've got enough logs now.
