### ISSUE TITLE
Some Settings Missing

### ISSUE THREAD

**Issue by MarioMario54321** [dimok789/loadiine_gx2#89]
On the version of Loadiine that I have, some of the settings are missing. These settings are all missing:

- Loader settings

Host IP
View game settings

- Game Settings

Hid-to-VPAD

I want to be able to use the Host IP setting to be able to use TCPGecko to connect with PyGecko, and I wanna be able to enable DLC.

**Comment by CreeperMario** [comment]
Do you mean that they're missing inside Loadiine GX2's settings interface, or they're missing in the configuration file? I've been able to access at least Host IP without trouble, but my build is a week or so old.

**Comment by MarioMario54321** [comment]
They're missing from the interface. If they're in the config file, how do I access them?

**Comment by CreeperMario** [comment]
Stick your SD Card into your computer (if you can) and navigate to `wiiu/apps/loadiine_gx2`. In that folder, there should be a configuration file called `loadiine_gx2.cfg` and, if you're interested, `loadiine_gx2_games.cfg`. Feel free to edit this using any PLAIN text editor (e.g. Notepad).

**Comment by MarioMario54321** [comment]
I already checked in there, and there's nothing there that can help. What do I put and where do I put it? Between where?

**Comment by MarioMario54321** [comment]
Never mind, I figured out you can put the Wii U in developer mode in the Internet Browser to have an IP to connect to, but still how can I access these options? And what about the option to enable DLC within the "aocxxxx..." folder?

**Comment by dibas** [comment]
Closing this issue because of the age of its last comment. Questions should go into the thread over at gbatemp.
