### ISSUE TITLE
Black screen NES Remix Pack EUR

### ISSUE THREAD

**Issue by Toastytwo** [dimok789/loadiine_gx2#9]
Can't get the damn game to start --> just a black screen, Loadiine 4 works just fine.
No server set up and waiting for the animation to settle didn't help.
Self-hosted, tried SD + WWW version..
Had the same problem with COD Ghosts, but apparently deleting the gx2 config file and starting from scratch sorted this one out.

Aside these small issues Dimok did ONE HELLUVA JOB! ;)

**Comment by dimok789** [comment]
Ok well, i didnt test that game and cant tell anything to it. I will see if someone from our guys has it for testing if not i will come back to you.

**Comment by scuba156** [comment]
NES Remix Pack EUR works fine here on 5.4.0EUR Loadiine Gx2. Just make sure you have the EUen sound files in '\content\sys\msgstudio' and if not then just copy USen to EUen.

**Comment by dimok789** [comment]
Hmm ok. This might be a user problem then. We need more people to test and verify it before searching for some possible problem in the application

**Comment by DaBlackDeath** [comment]
NES Remix Pack EUR works fine on 5.3.2 Loadiine GX2 selfhosted on WIFI-SDCard

**Comment by dimok789** [comment]
Ok so the issue is invalid. Must be something on your image then Toastytwo.

**Comment by dimok789** [comment]
Thanks to others for confirming.
