### ISSUE TITLE
Freeze whenever I try to load loadiine

### ISSUE THREAD

**Issue by Ohad1th** [dimok789/loadiine_gx2#90]
I have US 5.3.2 Wii u , tried both self hosting using this : http://gbatemp.net/threads/5-5-1-5-4-0-5-3-2-self-hosting-package-everything-in-one-zip-file.424679/#post-6310430

and web hosted wj44 and loadiine.ovh 
Tried latest stable release and also latest nightly build but nothing seems to be working , whenever I press the loadiine the screen just freezes , sometimes black screen sometimes just freezes on browser 
can't get it to work

**Comment by Ohad1th** [comment]
?

**Comment by dimok789** [comment]
Try loading the payload532.html directly from a self hosted apache server. It works all the time for me on 5.3.2.
