### ISSUE TITLE
[issue] Not generating cfg file

### ISSUE THREAD

**Issue by yoshisman8** [dimok789/loadiine_gx2#91]
Loadiine nightly a0c73ed doesnt seem to be generating a cfg file

**Comment by dimok789** [comment]
Hmm I dont think anything was changed in that direction. Do you maybe have the lock enabled on your SD card?

**Comment by yoshisman8** [comment]
upon further investigation i found out my wiiU is refusing to write to the SD card at all (regardless of lock possition) so its not a loadiine problem. Sorry for the false report
