### ISSUE TITLE
SSB crash when using separate updates folder

### ISSUE THREAD

**Issue by blockfeed** [dimok789/loadiine_gx2#99]
Game: Smash Bros (w/ v224 update, aka 1.1.5)
System: 5.3.2 (spoof to 5.5.1)
Build: a0c73ed nightly (5/11/2016) 

I was unable to use a separate updates folder when running a0c73ed nightly (5/11/2016) on 5.3.2 (spoofed to 5.5.1). When I used a separate updates folder, my system would crash with a 160-2200 error.

Smash Bros 1.1.5 (v224 update) runs properly under Mii Maker mode if you merge the code/content/meta folders from the the update into the main game.

Please let me know if you need additional info/testing.

**Comment by KitBallard64** [comment]
Several other games do this as well, like Minecraft and ZombiU (Eur). I just merge the updates into the core if they don't work as separate.

**Comment by Katkat95** [comment]
Simple question I merged the update file (224 V EU) with the main folder unfortunately I have black screen.

**Comment by Maschell** [comment]
Thanks for reporting, should be fixed now with the newest nightly (https://github.com/dimok789/loadiine_gx2/releases/tag/Loadiine-nightly-1c4b32c).

**Comment by blockfeed** [comment]
Confirmed fixed - SSB 1.1.6 (v288) runs properly.
